// <auto-generated />
namespace Grunch.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Authentication : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Authentication));
        
        string IMigrationMetadata.Id
        {
            get { return "201402220810313_Authentication"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
