// <auto-generated />
namespace Grunch.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create));
        
        string IMigrationMetadata.Id
        {
            get { return "201402201257474_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
