// <auto-generated />
namespace Grunch.Data
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class MenuDataObjects : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MenuDataObjects));
        
        string IMigrationMetadata.Id
        {
            get { return "201402201246361_MenuDataObjects"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
